# Generated by Django 5.2.1 on 2025-10-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time', models.TimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='aurora_backend.container')),
            ],
            options={
                'ordering': ['container', 'weekday', 'time'],
            },
        ),
    ]
