# Generated by Django 5.2.1 on 2025-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_backend', '0002_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['container', 'weekday', 'time', 'repeat']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
