# Generated by Django 5.2.1 on 2025-10-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_backend', '0003_alter_schedule_options_schedule_repeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['container', 'weekday', 'time']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repeat',
        ),
    ]
