# Generated by Django 5.2.1 on 2026-01-03 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_id', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small - 4 containers'), ('M', 'Medium - 6 containers'), ('L', 'Large - 10 containers')], max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('pill_name', models.CharField(max_length=100)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='dispensers.dispenser')),
            ],
            options={
                'ordering': ['slot_number'],
                'unique_together': {('dispenser', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('hour', models.PositiveSmallIntegerField()),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('repeat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dispensers.container')),
            ],
            options={
                'ordering': ['day_of_week', 'hour', 'minute'],
                'indexes': [models.Index(fields=['container', 'day_of_week'], name='dispensers__contain_c4f39a_idx')],
                'constraints': [models.UniqueConstraint(fields=('container', 'day_of_week', 'hour', 'minute'), name='uniq_schedule_per_container_time')],
            },
        ),
    ]
