# Generated by Django 5.2.1 on 2026-01-07 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slot_count', models.PositiveIntegerField(default=4)),
                ('serial_prefix', models.CharField(max_length=10, unique=True)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='serial_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='dispenser_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensers', to='dispensers.dispensermodel'),
        ),
    ]
