# Generated by Django 5.2.1 on 2026-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensers', '0002_dispensermodel_alter_dispenser_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='device_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='dirty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='schedule_version',
            field=models.BigIntegerField(default=1),
        ),
    ]
