# Generated by Django 5.2.1 on 2026-01-14 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensers', '0003_dispenser_device_secret_dispenser_dirty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('missed', 'missed')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dispensers.container')),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispensers.dispenser')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dispensers.schedule')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
