# Generated by Django 5.2.1 on 2025-12-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_first_name_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
